update

diff --git a/addkeywords b/addkeywords
--- a/addkeywords
+++ b/addkeywords
@@ -1,14 +1,14 @@
 #!/bin/bash
-# $Id: addkeywords,v 1.34 2019/05/14 20:14:34 fulford Exp fulford $
+# $Id: addkeywords,v 1.35 2019/05/14 20:20:04 fulford Exp fulford $
 # $Source: /src/admin/usr/local/etc/RCS/addkeywords,v $
-# $Revision: 1.34 $
+# $Revision: 1.35 $
 # Author C W Fulford.
 # Copyright 2019 (c) C W Fulford.
 # Licensed for public use under the LGPL, .
 # For assistance contact fulford@fulford.net 0793 572 8612
 ########################################################################
 cmd=`basename $0`
-ver=`echo "$Id: addkeywords,v 1.34 2019/05/14 20:14:34 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
+ver=`echo "$Id: addkeywords,v 1.35 2019/05/14 20:20:04 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
 syntax="$cmd [-c <configfile>] [-d] [-h <hostid>] [-v]|-V"
 while [ $# -gt 0 ] ;do
 	case $1 in 
@@ -18,7 +18,7 @@ while [ $# -gt 0 ] ;do
 		-l) last=$2;shift 2;;
 		-s) first=$2;shift 2;;
 		-v) verbose=:;shift;;
-		-V) echo "$cmd $Revision: 1.34 $ $Date: 2019/05/14 20:14:34 $"|awk '{print $1,$3,$6}';exit;;  
+		-V) echo "$cmd $Revision: 1.35 $ $Date: 2019/05/14 20:20:04 $"|awk '{print $1,$3,$6}';exit;;  
 		*) keywords="$keywords $1";shift;;
 	esac
 done
@@ -68,10 +68,12 @@ chkFiles () {
 		fi
 	done
 	if [ ${#gfiles} -gt 0 ];then
-		echo -e "\n\"$keyword\" already exists in ${#gfiles} files:">&2
+		count=`echo $gfiles|wc -w`
+		echo -e "\n\"$keyword\" already exists in $count files:">&2
 	fi
 	if [ ${#tfiles} -gt 0 ];then
-		echo -e "\"$keyword\" required in ${#tfiles} files\n">&2
+		count=`echo $tfiles|wc -w`
+		echo -e "\"$keyword\" required in $count files\n">&2
 		echo $tfiles|pr -t -8 -
 		retun ${#tfiles}
 	else
