update

diff --git a/addkeywords b/addkeywords
--- a/addkeywords
+++ b/addkeywords
@@ -1,14 +1,14 @@
 #!/bin/bash
-# $Id: addkeywords,v 1.86 2019/06/22 21:37:10 fulford Exp $
+# $Id: addkeywords,v 1.87 2019/06/23 21:45:56 fulford Exp fulford $
 # $Source: /src/admin/usr/local/etc/RCS/addkeywords,v $
-# $Revision: 1.86 $
+# $Revision: 1.87 $
 # Author C W Fulford.
 # Copyright 2019 (c) C W Fulford.
 # Licensed for public use under the LGPL, .
 # For assistance contact fulford@fulford.net 0793 572 8612
 ########################################################################
 cmd=`basename $0`
-ver=`echo "$Id: addkeywords,v 1.86 2019/06/22 21:37:10 fulford Exp $"|awk '{print $3,$4,$5}'`
+ver=`echo "$Id: addkeywords,v 1.87 2019/06/23 21:45:56 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
 syntax="$cmd [-c <configfile>] [-d] [-h <hostid>] [-v]|-V"
 while [ $# -gt 0 ] ;do
 	case $1 in 
@@ -18,7 +18,7 @@ while [ $# -gt 0 ] ;do
 		-l) last=$2;shift 2;;
 		-s) first=$2;shift 2;;
 		-v) verbose=:;shift;;
-		-V) echo "$cmd $Revision: 1.86 $ $Date: 2019/06/22 21:37:10 $"|awk '{print $1,$3,$6}';exit;;  
+		-V) echo "$cmd $Revision: 1.87 $ $Date: 2019/06/23 21:45:56 $"|awk '{print $1,$3,$6}';exit;;  
 		*) keywords="$keywords $1";shift;;
 	esac
 done
@@ -52,34 +52,32 @@ getFiles () {
 		clear
 		break
 	done
-	files=`ls *.$ext | awk '/'$first'/,/'$last'/{printf "%s ",$0}'`
-	return "$files"
+	farray=(`ls *.$ext | awk '/'$first'/,/'$last'/{printf "%s ",$0}'`)
 }
 
 chkFiles () {
 	keyword="$@"
-	tfiles=""
-	gfiles=""
-echo $files;read ought </dev/tty
-exit
-	for f in $files;do
-		if ! exiftool -IPTC:keywords $f|grep -q "$keyword"  ;then
-			tfiles="$tfiles $f"
+	for ((i=0; i<${#farray[@]}; i++));do
+		echo ${farray[$i]}
+		if ! exiftool -IPTC:keywords ${farray[$i]}|
+		  grep -q "$keyword";then
+			tfiles+=(${farray[$i]})
 		else
-			gfiles="$gfiles $f"
+			gfiles+=(${farray[$i]})
+			echo ${farray[$i]}
 		fi
+			echo tfiles ${tfiles[$i]}
+			echo gfiles ${gfiles[$i]}
 	done
-	if [ ${#gfiles} -gt 0 ];then
-		count=`echo $gfiles|wc -w`
-		echo -e "\n\"$keyword\" already exists in $count files:"
+	if [ ${#gfiles[@]} -gt 0 ];then
+		echo -e "\n\"$keyword\" already exists in ${#gfiles[@]} files:"
 	fi
-	if [ ${#tfiles} -gt 0 ];then
-		count=`echo $tfiles|wc -w`
-		echo -e "\n\"$keyword\" required in $count files"
+	if [ ${#tfiles[@]} -gt 0 ];then
+		echo -e "\n\"$keyword\" required in ${#tfiles[@]} files"
 		#echo $tfiles|pr -t -8 -
 		read -p "Add keyword[y/n/q]? " reply </dev/tty
 		case $reply  in
-			y) return $count;;
+			y) return ${#tfiles[@]};;
 			n) return 0;;
 			q) return -1;;
 		esac
@@ -95,8 +93,7 @@ chkKeyword () {
 	else
 		# Try partial match
 		IFS=: matches=(`awk '/'$keyword'/{printf "%s:",$0}' $dict`)
-		IFS=" 	
-"
+
 		# If nothing found offer to edit dictionary 
 		if [ ${#matches[@]} -lt 1 ];then
 			echo "Keyword \"$keyword\" is not available" >&2
@@ -108,20 +105,25 @@ chkKeyword () {
 			for ((i=0; i<${#matches[@]}; i++));do
 				echo "${i} ${matches[$i]}"
 			done
-			read -p "Select words or quit [#/q]: " c </dev/tty
-			keyword="${matches[$c]}"
+			read -p "Select words or quit [#/q]: " s </dev/tty
+			keyword="${matches[$s]}"
 		fi
 	fi
 }
 
 setKeyword () {
 	keyword="$@"
-	exiftool -IPTC:keywords+="$keyword" $tfiles
+	echo ${#tfiles[@]}
+	for ((i=0; i<${#tfiles[@]}; i++));do
+		echo target ${tfiles[$i]}
+		exiftool -IPTC:keywords+="$keyword" ${tfiles[$i]}
+	echo here
+	done
 	rm *original
 }
 
 ################# Main Procedure #####################
-export files=`getFiles`
+getFiles
 if [ ${#keywords} -lt 1 ];then
 	clear
 	echo 
@@ -129,13 +131,16 @@ if [ ${#keywords} -lt 1 ];then
 fi
 echo $keywords|awk -F, '{for(i=1; i<=NF; i++) print($i)}'|
 while read keyword;do
+echo $keyword
 	chkKeyword "$keyword"
+	gfiles=()
+	tfiles=()
 	chkFiles "$keyword" 
 	todo=$?
+	echo todo $todo
+	echo n ${#tfiles[@]}
 	if [ $todo -gt 0 ];then
 		setKeyword "$keyword"
-	elif [ $todo -lt 0 ];then
-		exit
 	fi
 done	
 echo "Keyword updates completed" 
