update

diff --git a/addkeywords b/addkeywords
--- a/addkeywords
+++ b/addkeywords
@@ -1,14 +1,14 @@
 #!/bin/bash
-# $Id: addkeywords,v 1.16 2019/05/14 19:30:00 fulford Exp fulford $
+# $Id: addkeywords,v 1.17 2019/05/14 19:31:52 fulford Exp fulford $
 # $Source: /src/admin/usr/local/etc/RCS/addkeywords,v $
-# $Revision: 1.16 $
+# $Revision: 1.17 $
 # Author C W Fulford.
 # Copyright 2019 (c) C W Fulford.
 # Licensed for public use under the LGPL, .
 # For assistance contact fulford@fulford.net 0793 572 8612
 ########################################################################
 cmd=`basename $0`
-ver=`echo "$Id: addkeywords,v 1.16 2019/05/14 19:30:00 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
+ver=`echo "$Id: addkeywords,v 1.17 2019/05/14 19:31:52 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
 syntax="$cmd [-c <configfile>] [-d] [-h <hostid>] [-v]|-V"
 while [ $# -gt 0 ] ;do
 	case $1 in 
@@ -18,7 +18,7 @@ while [ $# -gt 0 ] ;do
 		-l) last=$2;shift 2;;
 		-s) first=$2;shift 2;;
 		-v) verbose=:;shift;;
-		-V) echo "$cmd $Revision: 1.16 $ $Date: 2019/05/14 19:30:00 $"|awk '{print $1,$3,$6}';exit;;  
+		-V) echo "$cmd $Revision: 1.17 $ $Date: 2019/05/14 19:31:52 $"|awk '{print $1,$3,$6}';exit;;  
 		*) keywords="$keywords $1";shift;;
 	esac
 done
@@ -67,10 +67,10 @@ chkFiles () {
 		fi
 	done
 	if [ -${#gfiles} -gt 0 ];then
-		echo -e "\n\"$keyword\" already exists in $totdone files:"
+		echo -e "\n\"$keyword\" already exists in $totdone files:">&2
 	fi
 	if [ -${#tfiles} -gt 0 ];then
-		echo -e "\n\"$keyword\" required in ${#tfiles} files\n" 
+		echo -e "\n\"$keyword\" required in ${#tfiles} files\n">&2
 		echo $tfiles|pr -t -c 8 -
 		return ${#tfiles}
 	else
@@ -106,7 +106,7 @@ done
 getFiles
 echo $keywords|awk -F, '{for(i=1; i<=NF; i++) print($i)}'|
 while read keyword;do
-	if [ chkFiles -gt 0 ];then
+	if [ `chkFiles` -gt 0 ];then
 		for f in $tfiles ;do
 			setKeyword "$keyword"
 		done
