update

diff --git a/addkeywords b/addkeywords
--- a/addkeywords
+++ b/addkeywords
@@ -1,14 +1,14 @@
 #!/bin/bash
-# $Id: addkeywords,v 1.90 2020/04/03 10:02:00 fulford Exp $
+# $Id: addkeywords,v 1.91 2020/04/03 10:11:56 fulford Exp fulford $
 # $Source: /src/admin/usr/local/etc/RCS/addkeywords,v $
-# $Revision: 1.90 $
+# $Revision: 1.91 $
 # Author C W Fulford.
 # Copyright 2019 (c) C W Fulford.
 # Licensed for public use under the LGPL, .
 # For assistance contact fulford@fulford.net 0793 572 8612
 ########################################################################
 cmd=`basename $0`
-ver=`echo "$Id: addkeywords,v 1.90 2020/04/03 10:02:00 fulford Exp $"|awk '{print $3,$4,$5}'`
+ver=`echo "$Id: addkeywords,v 1.91 2020/04/03 10:11:56 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
 syntax="$cmd [-c <configfile>] [-d] [-f <first> [-l <last]]>]] [-s] [-u] [-v]|-V[<keyword>[,<keyword>][...]"
 while [ $# -gt 0 ] ;do
 	case $1 in 
@@ -20,7 +20,7 @@ while [ $# -gt 0 ] ;do
 		-s) set=0;shift;;
 		-u) ecase=0;shift;;
 		-v) verbose=:;shift;;
-		-V) echo "$cmd $Revision: 1.90 $ $Date: 2020/04/03 10:02:00 $"|awk '{print $1,$3,$6}';exit;;  
+		-V) echo "$cmd $Revision: 1.91 $ $Date: 2020/04/03 10:11:56 $"|awk '{print $1,$3,$6}';exit;;  
 		*) keywords="$keywords $1";shift;;
 	esac
 done
@@ -41,6 +41,15 @@ getFiles () {
 	*) echo "Extension for $dir unknown" >&2
 	   exit;;
    esac
+   # Does file exist
+   if [ ! -f *$first* ];then
+	echo "$cmd: $first not found" >&2
+	exit 1
+   fi
+   if [ ! -f *$last* ];then
+	echo "$cmd: $last not found" >&2
+	exit 1
+   fi
    if [ "$first" -a "$last" ];then	
 	first=${first}.${ext}
 	last=${last}.${ext}
@@ -63,14 +72,6 @@ getFiles () {
 }
 
 chkFiles () {
-	if [ ! -f *$first* ];then
-		echo "$cmd: $first not found" >&2
-		exit 1
-	fi
-	if [ ! -f *$last* ];then
-		echo "$cmd: $last not found" >&2
-		exit 1
-	fi
  
 	keyword="$@"
 	for ((i=0; i<${#farray[@]}; i++));do
@@ -148,7 +149,7 @@ setKeyword () {
 }
 
 ################# Main Procedure #####################
-getFiles
+getFiles || exit 1 
 if [ ${#keywords} -lt 1 ];then
 	clear
 	echo 
